### ISSUE TITLE
Issue compiling plugins

### ISSUE THREAD

**Issue by wimjongman** [sitemule/ILEastic#109]
I can `gmake all` just fine but `gmake plugins` is failing.

**Comment by wimjongman** [comment]
The modules create fine. I think it is because *LIBL is not set when building:

`	system -pieb "CRTSRVPGM SRVPGM(ILEASTIC/ILJWTPLUG) MODULE(ILEASTIC/JWTPLUGIN) BNDSRVPGM((*LIBL/ILEASTIC) (*LIBL/JSONXML) (*LIBL/JWT)) OPTION(*DUPPROC) DETAIL(*BASIC) STGMDL(*INHERIT) SRCFILE(ILEASTIC/QSRVSRC) TGTRLS(*CURRENT) TEXT('ILEastic - JWT Plugin')"`

Running this command manually after gmake fails works fine.

Also `gmake all plugins` is failing.

It is probably the plugins makefile that is not behaving correctly.

**Comment by m1h43l** [comment]
Thanks for pointing that out. Actually the `CRTSRVPGM` for JWT is not as intended. The Parameter `BNDSRVPGM` should have the variable `BIND_LIB` as a library and not `BIN_LIB`. BIN_LIB is nice because it compiles by default but then you have f. e. ILEASTIC as the library in the reference to the service program. Then it is not possible to move it to another library. So having *LIBL as a library for the BNDSRVPGM is ok but then you have the problem with the library list not correctly set during the make command.

Try adding `BIND_LIB=ILEASTIC` to the make command as a parameter like 
```
gmake BIND_LIB=ILEASTIC plugins
```

**Comment by wimjongman** [comment]
I have solved the issue, but I am looking for a flawless out-of-the-box experience. I also think the plugins should be built by `gmake all`

I will try to fix this and create a PR.

I also noticed that the JWT service program is now called ILJWTPLUG. This is different from the normal service program which is called JWT. Why did you decide to do that? Having the same service programs with a different name to bind to is not effective IMHO.
