### ISSUE TITLE
Compile Target Release V7R1M0 

### ISSUE THREAD

**Issue by sjmorales** [sitemule/ILEastic#68]
Is there a way to compile ILEastic with TGTRLS(V7R1M0)?  We have 60 machines with that version requirement.  

I think I had troubles with FastCGI if that is something we can remove from the compile.

**Comment by NielsLiisberg** [comment]
Thank you for your interest in ILEastic.

The code of ILEastic it self can be compiled back to 5.4, so mo problem there. The real issue here is the portotypes provided for RPG - and here I think it is about TR ( Technical refresh)  and not release. The issues I see here is: if you are willing to back-port the prototypes to D-specs this can be done. You can even use ILEastic without the rtnparm feature, simply by specifying the first parameter - that is the lefthand of the = sign. so

 text = il_getReqStr(pReq: 'input') 

can we rewritten to 

il_getReqStr(text : pReq : 'input') 

.. On 7.1. Another feature is the use of convert to/from UTF-8 since ILEastic internally only work on UTF-8 data. The last thing is varchar(4) where prior version of RPG only had varchar(2) .. I can not remember when the limit of 32K was removed.

So the answer : It can be done however 7.3 was the target for ILEastic from the beginning. 

If you are interested - I can ask management to set up a project for backwards compatibility for you, however I also think they will need a sponsor for that kind of projects.

**Comment by sjmorales** [comment]
We could probably be able to go with V7R2 as a minimum allowing for more free format flexibility.   If someone was interested in doing it in such a way where it could be maintained via compiler directives so that it could be part of the main repository and be done within a relatively short period of time, we could possibly talk with the money people to fund a sponsorship if we find we want to go this route.

**Comment by priosoft** [comment]
I will be fantastic if I could compile to 5.4 I have several customer based on this old release.

 

It is possible.?

 

Da: Niels Liisberg <notifications@github.com> 
Inviato: mercoledì 8 maggio 2019 00:16
A: sitemule/ILEastic <ILEastic@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: Re: [sitemule/ILEastic] Compile Target Release V7R1M0 (#68)

 

Thank you for your interest in ILEastic.

The code of ILEastic it self can be compiled back to 5.4, so mo problem there. The real issue here is the portotypes provided for RPG - and here I think it is about TR ( Technical refresh) and not release. The issues I see here is: if you are willing to back-port the prototypes to D-specs this can be done. You can even use ILEastic without the rtnparm feature, simply by specifying the first parameter - that is the lefthand of the = sign. so

text = il_getReqStr(pReq: 'input')

can we rewritten to

il_getReqStr(text : pReq : 'input')

.. On 7.1. Another feature is the use of convert to/from UTF-8 since ILEastic internally only work on UTF-8 data. The last thing is varchar(4) where prior version of RPG only had varchar(2) .. I can not remember when the limit of 32K was removed.

So the answer : It can be done however 7.3 was the target for ILEastic from the beginning.

If you are interested - I can ask management to set up a project for backwards compatibility for you, however I also think they will need a sponsor for that kind of projects.

**Comment by NielsLiisberg** [comment]
Target release can now go back to 7.2
